// Code generated by "stringer -type BaudRate -trimprefix BaudRate -output pkg/serial/baudrate_string.go pkg/serial/baudrate.go"; DO NOT EDIT.

package serial

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BaudRate4800-0]
	_ = x[BaudRate9600-1]
	_ = x[BaudRate19200-2]
	_ = x[BaudRate38400-3]
	_ = x[BaudRate57600-4]
	_ = x[BaudRate115200-5]
	_ = x[BaudRate230400-6]
	_ = x[BaudRate460800-7]
	_ = x[BaudRate921600-8]
	_ = x[BaudRate2000000-9]
}

const _BaudRate_name = "480096001920038400576001152002304004608009216002000000"

var _BaudRate_index = [...]uint8{0, 4, 8, 13, 18, 23, 29, 35, 41, 47, 54}

func (i BaudRate) String() string {
	if i < 0 || i >= BaudRate(len(_BaudRate_index)-1) {
		return "BaudRate(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BaudRate_name[_BaudRate_index[i]:_BaudRate_index[i+1]]
}
