// Code generated by "stringer -type CANBaudRate -trimprefix CANBaudRate"; DO NOT EDIT.

package xsens

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CANBaudRate1M-12]
	_ = x[CANBaudRate800k-11]
	_ = x[CANBaudRate500k-10]
	_ = x[CANBaudRate250k-0]
	_ = x[CANBaudRate125k-1]
	_ = x[CANBaudRate100k-2]
	_ = x[CANBaudRate83k3-3]
	_ = x[CANBaudRate62k5-4]
	_ = x[CANBaudRate50k-5]
	_ = x[CANBaudRate33k3-6]
	_ = x[CANBaudRate20k-7]
	_ = x[CANBaudRate10k-8]
	_ = x[CANBaudRate5k-9]
}

const _CANBaudRate_name = "250k125k100k83k362k550k33k320k10k5k500k800k1M"

var _CANBaudRate_index = [...]uint8{0, 4, 8, 12, 16, 20, 23, 27, 30, 33, 35, 39, 43, 45}

func (i CANBaudRate) String() string {
	if i < 0 || i >= CANBaudRate(len(_CANBaudRate_index)-1) {
		return "CANBaudRate(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CANBaudRate_name[_CANBaudRate_index[i]:_CANBaudRate_index[i+1]]
}
