// Code generated by "stringer -type CANBaudRateID -trimprefix CANBaudRateID"; DO NOT EDIT.

package xsens

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CANBaudRate1M-12]
	_ = x[CANBaudRate800k-11]
	_ = x[CANBaudRate500k-10]
	_ = x[CANBaudRate250k-0]
	_ = x[CANBaudRate125k-1]
	_ = x[CANBaudRate100k-2]
	_ = x[CANBaudRate83k3-3]
	_ = x[CANBaudRate62k5-4]
	_ = x[CANBaudRate50k-5]
	_ = x[CANBaudRate33k3-6]
	_ = x[CANBaudRate20k-7]
	_ = x[CANBaudRate10k-8]
	_ = x[CANBaudRate5k-9]
}

const _CANBaudRateID_name = "CANBaudRate250kCANBaudRate125kCANBaudRate100kCANBaudRate83k3CANBaudRate62k5CANBaudRate50kCANBaudRate33k3CANBaudRate20kCANBaudRate10kCANBaudRate5kCANBaudRate500kCANBaudRate800kCANBaudRate1M"

var _CANBaudRateID_index = [...]uint8{0, 15, 30, 45, 60, 75, 89, 104, 118, 132, 145, 160, 175, 188}

func (i CANBaudRateID) String() string {
	if i < 0 || i >= CANBaudRateID(len(_CANBaudRateID_index)-1) {
		return "CANBaudRateID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CANBaudRateID_name[_CANBaudRateID_index[i]:_CANBaudRateID_index[i+1]]
}
