// Code generated by "stringer -type CANDataIdentifier -trimprefix CANDataIdentifier"; DO NOT EDIT.

package xsens

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CANDataIdentifierInvalid-0]
	_ = x[CANDataIdentifierError-1]
	_ = x[CANDataIdentifierWarning-2]
	_ = x[CANDataIdentifierSampleTime-5]
	_ = x[CANDataIdentifierGroupCounter-6]
	_ = x[CANDataIdentifierUtcTime-7]
	_ = x[CANDataIdentifierStatusWord-17]
	_ = x[CANDataIdentifierQuaternion-33]
	_ = x[CANDataIdentifierEulerAngles-34]
	_ = x[CANDataIdentifierDeltaV-49]
	_ = x[CANDataIdentifierRateOfTurn-50]
	_ = x[CANDataIdentifierDeltaQ-51]
	_ = x[CANDataIdentifierAcceleration-52]
	_ = x[CANDataIdentifierFreeAcceleration-53]
	_ = x[CANDataIdentifierMagneticField-65]
	_ = x[CANDataIdentifierTemperature-81]
	_ = x[CANDataIdentifierBaroPressure-82]
	_ = x[CANDataIdentifierRateOfTurnHR-97]
	_ = x[CANDataIdentifierAccelerationHR-98]
	_ = x[CANDataIdentifierLatLong-113]
	_ = x[CANDataIdentifierAltitudeEllipsoid-114]
	_ = x[CANDataIdentifierPositionEcefX-115]
	_ = x[CANDataIdentifierPositionEcefY-116]
	_ = x[CANDataIdentifierPositionEcefZ-117]
	_ = x[CANDataIdentifierVelocityXYZ-118]
	_ = x[CANDataIdentifierGnssReceiverStatus-121]
	_ = x[CANDataIdentifierGnssReceiverDop-122]
}

const (
	_CANDataIdentifier_name_0 = "InvalidErrorWarning"
	_CANDataIdentifier_name_1 = "SampleTimeGroupCounterUtcTime"
	_CANDataIdentifier_name_2 = "StatusWord"
	_CANDataIdentifier_name_3 = "QuaternionEulerAngles"
	_CANDataIdentifier_name_4 = "DeltaVRateOfTurnDeltaQAccelerationFreeAcceleration"
	_CANDataIdentifier_name_5 = "MagneticField"
	_CANDataIdentifier_name_6 = "TemperatureBaroPressure"
	_CANDataIdentifier_name_7 = "RateOfTurnHRAccelerationHR"
	_CANDataIdentifier_name_8 = "LatLongAltitudeEllipsoidPositionEcefXPositionEcefYPositionEcefZVelocityXYZ"
	_CANDataIdentifier_name_9 = "GnssReceiverStatusGnssReceiverDop"
)

var (
	_CANDataIdentifier_index_0 = [...]uint8{0, 7, 12, 19}
	_CANDataIdentifier_index_1 = [...]uint8{0, 10, 22, 29}
	_CANDataIdentifier_index_3 = [...]uint8{0, 10, 21}
	_CANDataIdentifier_index_4 = [...]uint8{0, 6, 16, 22, 34, 50}
	_CANDataIdentifier_index_6 = [...]uint8{0, 11, 23}
	_CANDataIdentifier_index_7 = [...]uint8{0, 12, 26}
	_CANDataIdentifier_index_8 = [...]uint8{0, 7, 24, 37, 50, 63, 74}
	_CANDataIdentifier_index_9 = [...]uint8{0, 18, 33}
)

func (i CANDataIdentifier) String() string {
	switch {
	case i <= 2:
		return _CANDataIdentifier_name_0[_CANDataIdentifier_index_0[i]:_CANDataIdentifier_index_0[i+1]]
	case 5 <= i && i <= 7:
		i -= 5
		return _CANDataIdentifier_name_1[_CANDataIdentifier_index_1[i]:_CANDataIdentifier_index_1[i+1]]
	case i == 17:
		return _CANDataIdentifier_name_2
	case 33 <= i && i <= 34:
		i -= 33
		return _CANDataIdentifier_name_3[_CANDataIdentifier_index_3[i]:_CANDataIdentifier_index_3[i+1]]
	case 49 <= i && i <= 53:
		i -= 49
		return _CANDataIdentifier_name_4[_CANDataIdentifier_index_4[i]:_CANDataIdentifier_index_4[i+1]]
	case i == 65:
		return _CANDataIdentifier_name_5
	case 81 <= i && i <= 82:
		i -= 81
		return _CANDataIdentifier_name_6[_CANDataIdentifier_index_6[i]:_CANDataIdentifier_index_6[i+1]]
	case 97 <= i && i <= 98:
		i -= 97
		return _CANDataIdentifier_name_7[_CANDataIdentifier_index_7[i]:_CANDataIdentifier_index_7[i+1]]
	case 113 <= i && i <= 118:
		i -= 113
		return _CANDataIdentifier_name_8[_CANDataIdentifier_index_8[i]:_CANDataIdentifier_index_8[i+1]]
	case 121 <= i && i <= 122:
		i -= 121
		return _CANDataIdentifier_name_9[_CANDataIdentifier_index_9[i]:_CANDataIdentifier_index_9[i+1]]
	default:
		return "CANDataIdentifier(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
