// Code generated by "stringer -type CoordinateSystem -trimprefix CoordinateSystem"; DO NOT EDIT.

package xsens

import "strconv"

const (
	_CoordinateSystem_name_0 = "EastNorthUp"
	_CoordinateSystem_name_1 = "NorthEastDown"
	_CoordinateSystem_name_2 = "NorthWestUp"
)

func (i CoordinateSystem) String() string {
	switch {
	case i == 0:
		return _CoordinateSystem_name_0
	case i == 4:
		return _CoordinateSystem_name_1
	case i == 8:
		return _CoordinateSystem_name_2
	default:
		return "CoordinateSystem(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
