// Code generated by "stringer -type CoordinateSystem -trimprefix CoordinateSystem -output coordinatesystem_string.go coordinatesystem.go"; DO NOT EDIT.

package xsens

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CoordinateSystemEastNorthUp-0]
	_ = x[CoordinateSystemNorthEastDown-4]
	_ = x[CoordinateSystemNorthWestUp-8]
}

const (
	_CoordinateSystem_name_0 = "EastNorthUp"
	_CoordinateSystem_name_1 = "NorthEastDown"
	_CoordinateSystem_name_2 = "NorthWestUp"
)

func (i CoordinateSystem) String() string {
	switch {
	case i == 0:
		return _CoordinateSystem_name_0
	case i == 4:
		return _CoordinateSystem_name_1
	case i == 8:
		return _CoordinateSystem_name_2
	default:
		return "CoordinateSystem(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
