// Code generated by "stringer -type DataType -trimprefix DataType"; DO NOT EDIT.

package xsens

import "strconv"

const _DataType_name = "TemperatureUTCTimePacketCounterITOWGPSAgePressureAgeSampleTimeFineSampleTimeCoarseQuaternionRotationMatrixEulerAnglesBaroPressureDeltaVAccelerationFreeAccelerationAccelerationHRAltitudeEllipsoidPositionECEFLatLonGNSSPVTDataGNSSSatInfoRateOfTurnDeltaQRateOfTurnHRGPSDOPGPSSOLGPSTimeUTCGPSSVInfoMagneticFieldVelocityXYZStatusByteStatusWord"

var _DataType_map = map[DataType]string{
	2064:  _DataType_name[0:11],
	4112:  _DataType_name[11:18],
	4128:  _DataType_name[18:31],
	4144:  _DataType_name[31:35],
	4160:  _DataType_name[35:41],
	4176:  _DataType_name[41:52],
	4192:  _DataType_name[52:66],
	4208:  _DataType_name[66:82],
	8208:  _DataType_name[82:92],
	8224:  _DataType_name[92:106],
	8240:  _DataType_name[106:117],
	12304: _DataType_name[117:129],
	16400: _DataType_name[129:135],
	16416: _DataType_name[135:147],
	16432: _DataType_name[147:163],
	16448: _DataType_name[163:177],
	20512: _DataType_name[177:194],
	20528: _DataType_name[194:206],
	20544: _DataType_name[206:212],
	28688: _DataType_name[212:223],
	28704: _DataType_name[223:234],
	32800: _DataType_name[234:244],
	32816: _DataType_name[244:250],
	32832: _DataType_name[250:262],
	34864: _DataType_name[262:268],
	34880: _DataType_name[268:274],
	34944: _DataType_name[274:284],
	34976: _DataType_name[284:293],
	49184: _DataType_name[293:306],
	53264: _DataType_name[306:317],
	57360: _DataType_name[317:327],
	57376: _DataType_name[327:337],
}

func (i DataType) String() string {
	if str, ok := _DataType_map[i]; ok {
		return str
	}
	return "DataType(" + strconv.FormatInt(int64(i), 10) + ")"
}
