// Code generated by "stringer -type DataType -trimprefix DataType -output datatype_string.go datatype.go"; DO NOT EDIT.

package xsens

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DataTypeTemperature-2064]
	_ = x[DataTypeUTCTime-4112]
	_ = x[DataTypePacketCounter-4128]
	_ = x[DataTypeITOW-4144]
	_ = x[DataTypeGPSAge-4160]
	_ = x[DataTypePressureAge-4176]
	_ = x[DataTypeSampleTimeFine-4192]
	_ = x[DataTypeSampleTimeCoarse-4208]
	_ = x[DataTypeQuaternion-8208]
	_ = x[DataTypeRotationMatrix-8224]
	_ = x[DataTypeEulerAngles-8240]
	_ = x[DataTypeBaroPressure-12304]
	_ = x[DataTypeDeltaV-16400]
	_ = x[DataTypeAcceleration-16416]
	_ = x[DataTypeFreeAcceleration-16432]
	_ = x[DataTypeAccelerationHR-16448]
	_ = x[DataTypeAltitudeEllipsoid-20512]
	_ = x[DataTypePositionECEF-20528]
	_ = x[DataTypeLatLon-20544]
	_ = x[DataTypeGNSSPVTData-28688]
	_ = x[DataTypeGNSSSatInfo-28704]
	_ = x[DataTypeRateOfTurn-32800]
	_ = x[DataTypeDeltaQ-32816]
	_ = x[DataTypeRateOfTurnHR-32832]
	_ = x[DataTypeGPSDOP-34864]
	_ = x[DataTypeGPSSOL-34880]
	_ = x[DataTypeGPSTimeUTC-34944]
	_ = x[DataTypeGPSSVInfo-34976]
	_ = x[DataTypeMagneticField-49184]
	_ = x[DataTypeVelocityXYZ-53264]
	_ = x[DataTypeStatusByte-57360]
	_ = x[DataTypeStatusWord-57376]
}

const _DataType_name = "TemperatureUTCTimePacketCounterITOWGPSAgePressureAgeSampleTimeFineSampleTimeCoarseQuaternionRotationMatrixEulerAnglesBaroPressureDeltaVAccelerationFreeAccelerationAccelerationHRAltitudeEllipsoidPositionECEFLatLonGNSSPVTDataGNSSSatInfoRateOfTurnDeltaQRateOfTurnHRGPSDOPGPSSOLGPSTimeUTCGPSSVInfoMagneticFieldVelocityXYZStatusByteStatusWord"

var _DataType_map = map[DataType]string{
	2064:  _DataType_name[0:11],
	4112:  _DataType_name[11:18],
	4128:  _DataType_name[18:31],
	4144:  _DataType_name[31:35],
	4160:  _DataType_name[35:41],
	4176:  _DataType_name[41:52],
	4192:  _DataType_name[52:66],
	4208:  _DataType_name[66:82],
	8208:  _DataType_name[82:92],
	8224:  _DataType_name[92:106],
	8240:  _DataType_name[106:117],
	12304: _DataType_name[117:129],
	16400: _DataType_name[129:135],
	16416: _DataType_name[135:147],
	16432: _DataType_name[147:163],
	16448: _DataType_name[163:177],
	20512: _DataType_name[177:194],
	20528: _DataType_name[194:206],
	20544: _DataType_name[206:212],
	28688: _DataType_name[212:223],
	28704: _DataType_name[223:234],
	32800: _DataType_name[234:244],
	32816: _DataType_name[244:250],
	32832: _DataType_name[250:262],
	34864: _DataType_name[262:268],
	34880: _DataType_name[268:274],
	34944: _DataType_name[274:284],
	34976: _DataType_name[284:293],
	49184: _DataType_name[293:306],
	53264: _DataType_name[306:317],
	57360: _DataType_name[317:327],
	57376: _DataType_name[327:337],
}

func (i DataType) String() string {
	if str, ok := _DataType_map[i]; ok {
		return str
	}
	return "DataType(" + strconv.FormatInt(int64(i), 10) + ")"
}
