// Code generated by "stringer -type FixType -trimprefix FixType -output fixtype_string.go fixtype.go"; DO NOT EDIT.

package xsens

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FixTypeNoFix-0]
	_ = x[FixTypeDeadReckoningOnly-1]
	_ = x[FixType2DFix-2]
	_ = x[FixType3DFix-3]
	_ = x[FixTypeGNSSAndDeadReckoning-4]
	_ = x[FixTypeTimeOnly-5]
}

const _FixType_name = "NoFixDeadReckoningOnly2DFix3DFixGNSSAndDeadReckoningTimeOnly"

var _FixType_index = [...]uint8{0, 5, 22, 27, 32, 52, 60}

func (i FixType) String() string {
	if i >= FixType(len(_FixType_index)-1) {
		return "FixType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FixType_name[_FixType_index[i]:_FixType_index[i+1]]
}
