[[constraint]]
  branch = "master"
  name = "github.com/jacobsa/go-serial"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.9.1"

[prune]
  go-tests = true
  unused-packages = true
