[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/tarm/serial"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/alecthomas/kingpin"
  version = "2.2.6"

[[constraint]]
  branch = "master"
  name = "golang.org/x/xerrors"
