// Code generated by "stringer -type Precision -trimprefix Precision"; DO NOT EDIT.

package xsens

import "strconv"

const _Precision_name = "Float32FP1220FP1632Float64"

var _Precision_index = [...]uint8{0, 7, 13, 19, 26}

func (i Precision) String() string {
	if i >= Precision(len(_Precision_index)-1) {
		return "Precision(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Precision_name[_Precision_index[i]:_Precision_index[i+1]]
}
