// Code generated by MockGen. DO NOT EDIT.
// Source: go.bug.st/serial (interfaces: Port)

// Package mockserial is a generated GoMock package.
package mockserial

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	serial "go.bug.st/serial"
)

// MockPort is a mock of Port interface.
type MockPort struct {
	ctrl     *gomock.Controller
	recorder *MockPortMockRecorder
}

// MockPortMockRecorder is the mock recorder for MockPort.
type MockPortMockRecorder struct {
	mock *MockPort
}

// NewMockPort creates a new mock instance.
func NewMockPort(ctrl *gomock.Controller) *MockPort {
	mock := &MockPort{ctrl: ctrl}
	mock.recorder = &MockPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPort) EXPECT() *MockPortMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockPort) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockPortMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPort)(nil).Close))
}

// GetModemStatusBits mocks base method.
func (m *MockPort) GetModemStatusBits() (*serial.ModemStatusBits, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModemStatusBits")
	ret0, _ := ret[0].(*serial.ModemStatusBits)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModemStatusBits indicates an expected call of GetModemStatusBits.
func (mr *MockPortMockRecorder) GetModemStatusBits() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModemStatusBits", reflect.TypeOf((*MockPort)(nil).GetModemStatusBits))
}

// Read mocks base method.
func (m *MockPort) Read(arg0 []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockPortMockRecorder) Read(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockPort)(nil).Read), arg0)
}

// ResetInputBuffer mocks base method.
func (m *MockPort) ResetInputBuffer() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetInputBuffer")
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetInputBuffer indicates an expected call of ResetInputBuffer.
func (mr *MockPortMockRecorder) ResetInputBuffer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetInputBuffer", reflect.TypeOf((*MockPort)(nil).ResetInputBuffer))
}

// ResetOutputBuffer mocks base method.
func (m *MockPort) ResetOutputBuffer() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetOutputBuffer")
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetOutputBuffer indicates an expected call of ResetOutputBuffer.
func (mr *MockPortMockRecorder) ResetOutputBuffer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetOutputBuffer", reflect.TypeOf((*MockPort)(nil).ResetOutputBuffer))
}

// SetDTR mocks base method.
func (m *MockPort) SetDTR(arg0 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDTR", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDTR indicates an expected call of SetDTR.
func (mr *MockPortMockRecorder) SetDTR(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDTR", reflect.TypeOf((*MockPort)(nil).SetDTR), arg0)
}

// SetMode mocks base method.
func (m *MockPort) SetMode(arg0 *serial.Mode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMode", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMode indicates an expected call of SetMode.
func (mr *MockPortMockRecorder) SetMode(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMode", reflect.TypeOf((*MockPort)(nil).SetMode), arg0)
}

// SetRTS mocks base method.
func (m *MockPort) SetRTS(arg0 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRTS", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRTS indicates an expected call of SetRTS.
func (mr *MockPortMockRecorder) SetRTS(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRTS", reflect.TypeOf((*MockPort)(nil).SetRTS), arg0)
}

// SetReadTimeout mocks base method.
func (m *MockPort) SetReadTimeout(arg0 time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetReadTimeout", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetReadTimeout indicates an expected call of SetReadTimeout.
func (mr *MockPortMockRecorder) SetReadTimeout(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReadTimeout", reflect.TypeOf((*MockPort)(nil).SetReadTimeout), arg0)
}

// Write mocks base method.
func (m *MockPort) Write(arg0 []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *MockPortMockRecorder) Write(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockPort)(nil).Write), arg0)
}
