name: ci

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Sage
        uses: einride/sage/actions/setup@master
        with:
          go-version: 1.18

      - name: Make
        run: make

      - name: Report Code Coverage
        uses: codecov/codecov-action@v3
        with:
          file: .sage/build/go/coverage/go-test.txt
          fail_ci_if_error: true
